[alias]
a = "add"
b = "build"
bi = "binstall"
br = "build --release"
c = "clean"
ch = "check"
cl = "clippy"
d = "doc --open"
e = "espflash flash --monitor"
er = "espflash flash --release --monitor"
g = "generate"
gn = "generate esp-rs/esp-template"
gs = "generate esp-rs/esp-idf-template cargo"
i = "install"
iu = "install-update -a"
f = "fix"
m = "msrv"
t = "test"
un = "udeps"
up = "update"
r = "run"
rr = "run --release"
sem = "semver-checks check-release"
s = "sort"
