# Load Espressif toolchain environment from the export file generated by espup.
#
# espup generates a POSIX shell script by default at $HOME/export-esp.sh.
# Fish cannot source that file directly, so we read the relevant exports and
# apply them here.

set -l espup_export_file "$HOME/export-esp.sh"
if set -q ESPUP_EXPORT_FILE
    set espup_export_file "$ESPUP_EXPORT_FILE"
end

if test -f "$espup_export_file"
    while read -l line
        set line (string trim --chars '\r' -- "$line")

        if string match -qr '^export PATH=' -- "$line"
            set -l espup_bin (string replace -r '^export PATH="?([^"]*):\$PATH"?$' '$1' -- "$line")
            if test "$espup_bin" != "$line"
                if not contains -- "$espup_bin" $PATH
                    set -gx PATH "$espup_bin" $PATH
                end
            else
                set -l espup_path (string replace -r '^export PATH="?([^"]*)"?$' '$1' -- "$line")
                set -gx PATH (string split ':' -- "$espup_path")
            end
        else if string match -qr '^export LIBCLANG_PATH=' -- "$line"
            set -gx LIBCLANG_PATH (string replace -r '^export LIBCLANG_PATH="?([^"]*)"?$' '$1' -- "$line")
        end
    end < "$espup_export_file"
end
